version: "3.5"

services:
    basic-php:
        image: php:8.0-apache
        build: .
        volumes:
            - './:/var/www/html'
        environment:
            - XDEBUG_CONFIG
            - PHP_IDE_CONFIG
        ports:
            - "${HTTP_PORT:-80}:80"
            - "${HTTPS_PORT:-443}:443"
        extra_hosts:
            - "host.docker.internal:host-gateway"
