main:
  path: /
  methods: ['GET']
  controller: Xvladx\Controller\MainController::indexAction

blog.list:
  path: /blog
  methods: ['GET']
  controller: Xvladx\Controller\BlogController::listAction

blog.specific_entry:
  path: /blog/{year}/{month}/{day}
  methods: ['GET']
  controller: Xvladx\Controller\BlogController::entryAction
  requirements:
    year: '\d{4}'
    month: '\d{2}'
    day: '\d{2}'
